name: CI

on:
  push:
    branches: [ master ]
    tags: "*.*.*"
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-24.04, # x64
            ubuntu-24.04-arm, # ARM
          ]
        # syntax explanation:
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations
        include:
          - os: ubuntu-24.04
            artifact-folder: linux
          - os: ubuntu-24.04-arm
            artifact-folder: linuxarm64

    runs-on: ${{matrix.os}}

    steps:
    # needed for Windows testing
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - run: npm config set audit false
    - run: npm config set fund false
    - run: npm ci
